<?php
namespace backend\controllers;

use backend\component\CController;
use backend\repositories\ArticleRepository;
use general\models\ZhihuAnswer;
use general\models\ZhihuArticle;
use general\models\ZhihuMember;
use general\models\ZhihuQuestion;
use backend\repositories\QuestionRepository;
use Yii;
use yii\base\Module;
use yii\helpers\Json;
use yii\web\Controller;

/**
 * 问题控制器
 */
class ArticleController extends CController
{



    /**
     * Displays homepage.
     *
     * @return string
     */
    public $layout = false;
    public $enableCsrfValidation = false;

    /**
     * 问题资源库
     * @var QuestionRepository
     */
    private $articleRepository;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function __construct($id, Module $module, array $config = [])
    {
        $this->articleRepository = new ArticleRepository();
        parent::__construct($id, $module, $config);
    }

    /*
     * 问题列表
     */
    public function actionIndex()
    {
        $data = file_get_contents('php://input');
        $data = Json::decode($data);

        $result = $this->articleRepository->findAll($data);

        return $this->success($result['data'],$result['count']);
    }

    public function actionDelete(){
        $data = file_get_contents('php://input');
        $data = Json::decode($data);

        ZhihuArticle::deleteAll(['id'=>$data['id']]);

        return Json::encode(['code' => 0, 'data' => []]);
    }

    /**
     * 问题列表
     * @return mixed
     */
    public function actionGetAnswerList(){
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $answers = $this->page(ZhihuAnswer::find()->where(['question_id'=>$data['id']]))->asArray()->all();
        $authors = ZhihuMember::find()->select('username')->indexBy('id')->column();
        foreach ($answers as $k=>$v){
            $answers[$k]['author_name'] = $authors[$v['author_id']];
            $answers[$k]['create_time'] = date('Y-m-d',$v['create_time']);
        }
        $count = ZhihuAnswer::find()->where(['question_id'=>$data['id']])->count();
        return $this->success($answers,$count);
    }


    /**
     * 问题详情
     * @return string
     */
    public function actionDetail()
    {
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $result = $this->articleRepository->one($data);
        return Json::encode(['code' => 0, 'data' => $result]);
    }

    /*
     * 保存文章
     */
    public function actionSave(){
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $id= !empty($data['id'])?$data['id']:0;
        $question =  !empty(ZhihuArticle::findOne(['id'=>$id]))?ZhihuArticle::findOne(['id'=>$id]):new ZhihuArticle();
        $question->title = $data['title'];
        $question->content = $data['content'];
        $question->author_id = $data['author_id'];
        $question->create_time = time();
        $question->save();
        return Json::encode(['code' => 0]);
    }








}
