<?php
namespace backend\controllers;

use backend\component\CController;
use general\models\ZhihuAnswer;
use general\models\ZhihuMember;
use general\models\ZhihuQuestion;
use Yii;

/**
 * Site controller
 */
class HomeController extends CController
{
    

    /**
     * Displays homepage.
     *
     * @return string
     */

    public $layout=false;
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $result = [];
        $result['answer_count'] = ZhihuAnswer::find()->count();
        $result['question_count'] = ZhihuQuestion::find()->count();
        $result['user_count'] = ZhihuMember::find()->count();
        $result['like_count'] = ZhihuAnswer::find()->select('SUM(up_count)')->scalar();
        return $this->success($result);
    }

}
