<?php
namespace backend\controllers;

use backend\component\CController;
use general\models\ZhihuAnswer;
use general\models\ZhihuMember;
use general\models\ZhihuQuestion;
use backend\repositories\QuestionRepository;
use Yii;
use yii\base\Module;
use yii\helpers\Json;
use yii\web\Controller;

/**
 * 问题控制器
 */
class QuestionController extends CController
{



    /**
     * Displays homepage.
     *
     * @return string
     */
    public $layout = false;
    public $enableCsrfValidation = false;

    /**
     * 问题资源库
     * @var QuestionRepository
     */
    private $questionRepository;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function __construct($id, Module $module, array $config = [])
    {
        $this->questionRepository = new QuestionRepository();
        parent::__construct($id, $module, $config);
    }

    /*
     * 问题列表
     */
    public function actionIndex()
    {
        $data = file_get_contents('php://input');
        $data = Json::decode($data);

        $result = $this->questionRepository->findAll($data);

        return $this->success($result['data'],$result['count']);
    }

    public function actionDelete(){
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        //ZhihuQuestion::deleteAll(['id'=>$data['id']]);
        $page_size = isset($data['pageSize'])?$data['pageSize']:5;
        $next_question = ZhihuQuestion::find()->offset(($data['page'])*$page_size)->limit(1);//->one();

        print_r($next_question);exit;

        return Json::encode(['code' => 0, 'data' => $next_question]);
    }

    /**
     * 问题列表
     * @return mixed
     */
    public function actionGetAnswerList(){
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $answers = $this->page(ZhihuAnswer::find()->where(['question_id'=>$data['id']]))->asArray()->all();
        $authors = ZhihuMember::find()->select('username')->indexBy('id')->column();
        foreach ($answers as $k=>$v){
            $answers[$k]['author_name'] = $authors[$v['author_id']];
            $answers[$k]['create_time'] = date('Y-m-d',$v['create_time']);
        }
        $count = ZhihuAnswer::find()->where(['question_id'=>$data['id']])->count();
        return $this->success($answers,$count);
    }


    /**
     * 问题详情
     * @return string
     */
    public function actionDetail()
    {
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $result = $this->questionRepository->one($data);
        return Json::encode(['code' => 0, 'data' => $result]);
    }

    public function actionSave(){
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $question = ZhihuQuestion::findOne(['id'=>$data['id']]);
        $question->title = $data['title'];
        $question->content = $data['content'];
        $question->save();
        return Json::encode(['code' => 0]);
    }





}
