<?php
namespace frontend\controllers;

use frontend\component\CController;
use general\models\ArticleComment;
use general\models\BatteArray;
use general\models\Member;
use general\models\ZhihuArticle;
use Yii;
use yii\helpers\Json;

class BattlearrayController extends CController
{


    /**
     * Displays homepage.
     *
     * @return string
     */
    public $layout = false;
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * 列表
     * @return string
     */
    public function actionList()
    {
        $page_size = 5;
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $page = $data['page'];
        $result = BatteArray::find()->offset(($page-1)*($page_size))->limit($page_size)
            ->asArray()->all();
        foreach ($result as $k=>$v){
            $result[$k]['heros'] = json_decode($v['heros'],1);
            $result[$k]['create_time'] = date('Y-m-d',$v['create_time']);
        }

        return $this->success($result,BatteArray::find()->count());
    }

    /**
     * 详情
     * @return string
     */
    public function actionDetail()
    {

        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $result = BatteArray::findOne(['id'=>$data['id']]);
        $result['hero_equipments'] = json_decode($result['hero_equipments'],1);
        $result['heros'] = json_decode($result['heros'],1);
        return Json::encode(['code' => 0, 'data' => $result]);
    }

    /**
     * 保存阵容
     * @return string
     */
    public function actionSave(){
        $data = file_get_contents('php://input');
        $data = Json::decode($data);
        $id = empty($data['id'])?0:$data['id'];
        $result = BatteArray::findOne(['id'=>$id]);
        $battle = empty($result)?new BatteArray():$result;
        $battle->title = $data['title'];
        $battle->heros = Json::encode($data['heros']);
        $battle->playway = $data['playway'];
        $battle->hero_equipments = Json::encode($data['hero_equipments']);
        $battle->update_time = time();
        $battle->create_time = time();
        if(!$battle->save()){
            print_r($battle->getErrors());
        }
        return Json::encode(['code' => 0]);
    }


}
