<?php
namespace frontend\controllers;

use general\models\Bike;
use general\models\ChatRecord;
use general\models\Hongbao;
use general\models\Member;
use Yii;
use yii\helpers\Json;
use yii\web\Controller;

class ChatController extends Controller
{
    

    /**
     * Displays homepage.
     *
     * @return string
     */
    public $layout=false;
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: *");
        header("Access-Control-Allow-Credentials: true");
        header("Access-Control-Allow-Methods: POST, GET, OPTIONS");
        header("Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With");
        header('P3P: CP="CAO PSA OUR"'); // Makes IE to support cookies
        header("Content-Type: application/json; charset=utf-8");
    }

    public function actionIndex()
    {
    	//333
        $member= Member::findOne(1);
        return Json::encode($member);
    }

    public function actionSavechatrecord(){
        $data=file_get_contents('php://input');
        $data = Json::decode($data);
        $r=ChatRecord::findOne(1);
        $r->content=Json::encode($data['content']) ;
        $r->update_time=time();
        $r->save(false);
        //$data=Json::decode($data);
    }

    public function actionGetchatrecord(){
        $r=ChatRecord::findOne(1);
        return $r->content;
    }


}
