<?php
namespace frontend\controllers;

use general\models\Bike;
use general\models\Member;
use general\models\RepairRecords;
use general\models\RidingRecord;
use Yii;
use yii\helpers\Json;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * 商品测试控制器
 */
class ProductController extends Controller
{


    /**
     * Displays homepage.
     *
     * @return string
     */
    public $layout = false;
    public $enableCsrfValidation = false;

    public function init()
    {
        header("Access-Control-Allow-Origin: *");
        header("Access-Control-Allow-Credentials: true");
        header("Access-Control-Allow-Methods: POST, GET, OPTIONS");
        header("Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With");
        header('P3P: CP="CAO PSA OUR"'); // Makes IE to support cookies
        header("Content-Type: application/json; charset=utf-8");
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $p = [
            ['name' => '施巴婴儿洁肤浴露400ml', 'norm' => '规格:400ml/瓶', 'price' => '158.00', 'original_price' => '161.00', 'image' => ["img/product_1.jpg"]],
            ['name' => '施巴婴儿洁肤浴露200ml', 'norm' => '规格:200ml/瓶', 'price' => '140.00', 'original_price' => '161.00', 'image' => ["img/product_1_2.jpg"]],
            ['name' => '施巴婴儿洁肤浴露300ml', 'norm' => '规格:300ml/瓶', 'price' => '130.00', 'original_price' => '161.00', 'image' => ["img/product_2_1.jpg"]]
        ];

        return Json::encode($p);
    }

}
